config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"
  # post "/", to: "welcome#crae"
  resources :welcome, path: ""

  authenticated :user do
    root 'dashboard/urls#index'
  end

  namespace :dashboard do 
  	resources :urls
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/session_url.rb
class SessionUrl < ApplicationRecord
	# this class used to establish the relation between session and url has_many  
	belongs_to :url
end

app/models/url.rb
class Url < ApplicationRecord
	# this class is using to store all records for Url data 
	validates_presence_of :long_url
	validates_uniqueness_of :long_url, scope: :user_id, if: Proc.new{self.user_id.present?}	# condition for instance if having user then check uniqueness of long_url
	
	belongs_to :user, optional: true
	has_many :session_urls # assocition needed in case of session user only to ignore creation of multiple url for the same long_url 

	before_create :create_token # callback to set a unique token for minified url
	before_create :create_session_url # create association  


	def to_param
		token
	end

	# use to set the value of token secure 
	def create_token
		self.token = SecureRandom.hex(4)
	end

	# to make the associated object of session_urls table if user is not logged in
	def create_session_url
		if self.session_id.present?
			self.session_urls.new(session_id: self.session_id)
		end
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :urls 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base	
end

app/controllers/dashboard/urls_controller.rb
class Dashboard::UrlsController < ApplicationController
	before_action :authenticate_user!	
	before_action :set_url, only: [:edit, :update, :destroy, :show]

	def index # to get a new object of url and already existed urls for current user
		@urls = current_user.urls
		@url = Url.new
	end

	def create # to 
		@url = current_user.urls.new(url_params)

		if @url.save
			flash[:success] = "Url has been successfully shortened"
			redirect_to dashboard_urls_path
		else
			flash[:error] = "#{@url.errors.full_messages.join(',')}"
			redirect_back(fallback_location: root_url)
		end
	end

	def edit		
	end

	def update # action to update the title of url
		if @url.update(url_params)
			flash[:success] = "Url has been updated successfully"
			redirect_back(fallback_location: root_url)
		else
			flash[:error] = "#{@url.errors.full_messages.join(',')}"
			redirect_back(fallback_location: root_url)
		end
	end

	def show
		
	end

	def destroy
		if @url.destroy
			flash[:success] = "Url has been deleted successfully"
			redirect_to dashboard_urls_path
		else
			flash[:error] = "#{@url.errors.full_messages.join(',')}"
			redirect_to dashboard_urls_path
		end 	
	end

	private

		def url_params
			params.require(:url).permit(:long_url, :title)
		end

		def set_url # common method to set url object
			@url = current_user.urls.find_by(token: params[:id])
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_action :check_user_is_guest?, except: :show
	include ApplicationHelper

	def index
		@url = Url.new
	end

	# action to redirect shorted link to actual link
	def show 
		@url = Url.find_by(token: params[:id])
		if @url.present?
			redirect_to @url.long_url
		end
	end

	# action to check existing link for this long_url and create if does not exist
	def create 
		@existing_url = Url.find_by(long_url: params[:url][:long_url])			
		
		if @existing_url.present?	
			@existing_url.session_urls.find_or_create_by(session_id: session.id)
			flash[:warning] = "Url has been shortened"
			redirect_back(fallback_location: root_url)
		else
			@url = Url.new(url_params)	
			if @url.save
				flash[:success] = "Url has shortened successfully"
				redirect_back(fallback_location: root_url)
			else
				flash[:error] = "#{@url.errors.full_messages.join(',')}"
				render (:index)
			end
		end
	end	

	private
		
		def url_params
			params.require(:url).permit(:long_url, :session_id)
		end

		def check_user_is_guest? # before action to check if user is logged in then switch to dashboard url controller
			if user_signed_in? 
				redirect_to dashboard_urls_path
			end
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def urls_from_session
		session_urls = SessionUrl.where(session_id: session.id).order("created_at desc")
		session_urls.collect(&:url).compact
	end
end

app/helpers/dashboard/urls_helper.rb
module Dashboard::UrlsHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/urls/_form.html.slim
-if params["action"] == "edit"
	.form-group
		= f.text_field :title, class:"form-control", placeholder: "Title"
.form-group
	= f.text_field :long_url,class:"form-control", placeholder: "Place a link to shorten it", disabled: (params["action"] == "edit" ? true : false), required: true

app/views/dashboard/urls/edit.html.slim
.col-md-6.col-md-offset-3
	.panel.panel-default
		.panel-heading
			h1 Short your link here
		.panel-body
			= form_for [:dashboard, @url] do |f|
				=render "form",f: f
				.form-group	
					= f.submit "Update link", class: "btn btn-primary"

app/views/dashboard/urls/index.html.slim
-unless @urls.blank?
	.col-md-6
		.panel.panel-default
			.panel-body
				-@urls.each do |url|
					li 
						-if url.title.present?
							h4= url.title 
						=link_to "#{welcome_url(url)}", welcome_path(url), target: "_blank"
						p
							small =truncate url.long_url, length: 150
							=link_to "<i class='fa fa-edit'></i>".html_safe, edit_dashboard_url_path(url), class:"btn btn-warning", title: "Edit"
							|&nbsp;
							=link_to "show", dashboard_url_path(url), class:"btn btn-success"
							|&nbsp;
							=link_to "<i class='fa fa-trash'></i>".html_safe, dashboard_url_path(url), class:"btn btn-danger", data: {confirm: "Are you sure", toggle: "tooltip"}, title: "Remove", method: :delete
			

.col-md-6 class=(@urls.blank? ? "col-md-offset-3" : "")
	.panel.panel-default
		.panel-heading
			h1 Short your link here
		.panel-body
			= form_for [:dashboard, @url] do |f|
				=render "form",f: f
				.form-group	
					= f.submit "Short link", class: "btn btn-primary"

app/views/dashboard/urls/show.html.slim
.col-md-12
	.panel.panel-default
		.panel-heading
			h3 =@url.title
		.panel-body
			table.table.table-striped.table-bordered				
				tr
					td User
					td =@url.user.email
				tr
					td Title
					td =@url.title
				tr
					td Actual link
					td =link_to "#{@url.long_url}", @url.long_url	, target: "_blank"
				tr
					td Craigly	
					td =link_to "#{welcome_url(@url)}", welcome_url(@url)	, target: "_blank"
				tr
					td Created
					td =@url.created_at.strftime("%d-%m-%Y")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Craig</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render partial: "shared/header"%>
    <%= flash_messages(:close) %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.slim
nav.navbar.navbar-default
  .container-fluid
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle.collapsed aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="/"  Craig
    /! Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        -if user_signed_in?
          li
            a href=dashboard_urls_path Urls
          li
            a data-method="delete" href=destroy_user_session_path Sign out
  
        -else
          li
            a href=new_user_session_path  Login
          li
            a href=new_user_registration_path  Signup
          

app/views/welcome/index.html.slim
.row
	.col-md-6.col-md-offset-3
		.panel.panel-default
			.panel-heading
				h1 Short your link
			.panel-body
				= form_for @url, url: welcome_index_path do |f|
					= f.hidden_field :session_id, value: session.id
					.form-group
						= f.text_field :long_url,class:"form-control", placeholder: "Place a link to shorten it", required: true
					.form-group	
						= f.submit "Short link", class:"btn btn-primary"

				-if urls_from_session.any?	
					ul
						-urls_from_session.each do |url|
							li 
								=link_to "#{welcome_url(url)}", welcome_path(url), target: "_blank"
								p
									small =truncate url.long_url, length: 150
						